backend:
  replicaCount: 2
  image:
    repository: vijaykardak/smart-farm-back
    tag: v1
    pullPolicy: IfNotPresent
  service:
    port: 5000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  env:
    MONGO_DB: smartfarm
    CORS_ORIGINS: "*"
    SEED_ON_START: "false"
  existingSecret: smart-farm-secrets

frontend:
  replicaCount: 2
  image:
    repository: vijaykardak/smart-farm-front
    tag: v1
    pullPolicy: IfNotPresent
  service:
    port: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 256Mi

ingress:
  enabled: false
  className: nginx
  host: smart-farm.example.com
  tls: []

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

podDisruptionBudget:
  enabled: true
  minAvailable: 1
fullnameOverride: smart-farm
