apiVersion: v1
kind: Service
metadata:
  name: {{ include "smart-farm.fullname" . }}-frontend
  labels:
    {{- include "smart-farm.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "smart-farm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
