apiVersion: v1
kind: Service
metadata:
  name: smart-farm-backend
  namespace: smart-farm
  labels:
    app: smart-farm
    component: backend
spec:
  type: ClusterIP
  selector:
    app: smart-farm
    component: backend
  ports:
    - name: http
      port: 5000
      targetPort: http
