apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: smart-farm-backend
  namespace: smart-farm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smart-farm-backend
  minReplicas: 2
  maxReplicas: 5
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
    scaleDown:
      stabilizationWindowSeconds: 300
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: smart-farm-frontend
  namespace: smart-farm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smart-farm-frontend
  minReplicas: 2
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
