apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: smart-farm-backend
  namespace: smart-farm
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: smart-farm
      component: backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: smart-farm-frontend
  namespace: smart-farm
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: smart-farm
      component: frontend
